version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: .
      dockerfile: dockerfile_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - '8000:8000'
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: .
      dockerfile: dockerfile_frontend
    ports:
      - '8501:8501'
    depends_on:
      - backend
    restart: always

volumes:
  pgdata: